# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Google I/O Extended Suwon
email: gdg.suwon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Google I/O Extended Suwon은 Google I/O 에서 발표된 내용 중  함께 더  알아가면 좋았을 것 같은 내용을  수원지역에 계신 개발자 분들과 함께 공유하는 자리입니다. 
baseurl: "https://facebook.com/groups/gdgsuwon" # the subpath of your site, e.g. /blog
url: "http://gdgsuwon.github.io/ioextended" # the base hostname & protocol for your site
twitter_username: gdgsuwon
github_username:  gdgsuwon

# Build settings
markdown: kramdown
